version: '2'

services:
  postgres:
      image: postgres:alpine
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE}
      ports:
        - 5432:5432
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/00-init.sql

  application:
    env_file: ./.env
    image: php:7.1
    volumes:
      - ${APPLICATION_PATH}:/phpapp
    links:
      - postgres
    command: php /phpapp/artisan serve --host=0.0.0.0 --port=80
    ports:
      - 80:80
